Feature/automaton deploy script
lidofinance/lido-l2-optimism pull request #42
Opened 2024-12-05 12:03 UTC by kovalgek

2025-01-13 17:40 UTC, arwer13 requested changes

2025-01-13 17:40 UTC, arwer13 commented on scripts/optimism/cross-chain-relayer.ts
> +  const optimismPortalAddress = env.address("L1_L2_PORTAL", "0x16Fc5058F25648194471939df75CF27A2fdC48BC");
Should `L1_L2_PORTAL` be in .env.example and README?

2025-01-13 17:40 UTC, arwer13 commented on scripts/optimism/deploy-automaton.ts
> +import env from "../../utils/env";
A dedicated deploy script for external tool is not a clear dependency flow, could we go without it and utilize some existing deploy script?

2025-01-13 17:40 UTC, arwer13 commented on scripts/optimism/update-ethereum-executor.ts
> +  const networkName = "sepolia";
Should 'sepolia' be hardcoded here?

2025-01-13 17:40 UTC, arwer13 commented on utils/deployment.ts
> +interface L1AutomatonDeploymentConfig extends BridgingManagerSetupConfig {
Could Automaton mentions be avoided? In favour of smth like just "L1DeploymentConfig"?

2025-01-13 17:40 UTC, arwer13 commented on utils/deployment.ts
> -  console.log(`${pad}· l1TokenBridge: ${chalk.underline(params.l1TokenBridge)}`);
Why this and other fields have gone?

2025-01-13 17:40 UTC, arwer13 commented on utils/deployment/DeployScript.ts
> +          return console.error(err);
```suggestion
        return console.error(err);
```

2025-01-13 17:40 UTC, arwer13 commented on utils/optimism/testing.ts
> +  //console.log(`  · Network Id: ${networkName}`);
?

2025-01-13 17:40 UTC, arwer13 commented on utils/prompt.ts
> +  if (process.env.L2_DEPLOY_SKIP_PROMPTS) {
Let's add it to .env.example and maybe to README

2025-01-14 18:20 UTC, kovalgek commented on scripts/optimism/update-ethereum-executor.ts
> +  const networkName = "sepolia";
I'm not sure this script will be used ever

2025-01-20 10:51 UTC, tamtamchik reviewed
I'm sorry this is a very big PR, and I don't have enough time to go through it thoroughly. Just added my 2 cents.

2025-01-20 10:51 UTC, tamtamchik commented on .env.example
> +L1_CHAIN_ID=10
Add comment: what is 10?

2025-01-20 10:51 UTC, tamtamchik commented on .env.example
> +L2_CHAIN_ID=11155420
Add a comment: what is 11155420?

2025-01-20 10:51 UTC, tamtamchik commented on .env.example
> +L2_BLOCK_EXPLORER_API_KEY=
Etherscan v2 uses the same key for all the chains now, do we need to have a separation here? 
https://docs.etherscan.io/etherscan-v2#single-api-key

2025-01-22 10:05 UTC, kovalgek commented on .env.example
> +L2_BLOCK_EXPLORER_API_KEY=
Soneium uses blockscout and it has a different key.

2025-01-23 18:14 UTC, arwer13 approved these changes

2025-01-24 12:50 UTC, merged